project_id = "znffhxidyoemzsenshge"

[functions.parse-workflow-command]
verify_jwt = false

[functions.execute-workflow]
verify_jwt = false

[functions.setup-workflow-schedule]
verify_jwt = false

[functions.pipedream-oauth-exchange]
verify_jwt = true

[functions.analyze-deal-document]
verify_jwt = true
